### PR TITLE
eec-cegar

### PR DESCRIPTION
**Pull request by pevalme**
I have modified mist to let the user choose the eec-cegar algorithm and also modified the test script to work with this new version of the tool.

I don't know what should mist write to explain the eec-cegar algorithm when displaying help.

### CODE REVIEW

**Comment by pierreganty** [comment]
solves #15

**Comment by pierreganty** [comment]
Please, run the tests so as to make sure that the output of eec-cegar is consistent with the other algorithm.

**Comment by pierreganty** [comment]
Also update the necessary markdown files including `README.md` to reflect this change.
Unfortunately there is no publication that explains this new algorithm.

**Comment by pevalme** [comment]
I have already run the tests and the eec-cegar algorithm works fine.

I'm going to modify the README.md
Please, check the new help menu because I'm not sure about what I wrote there

**Comment by pierreganty** [comment]
There is no document defining the `eec-cegar` anywhere.
Before coming up with a definite solution, we could perhaps write a small page in the wiki with the basic features of the algorithm.

**Comment by pierreganty** [comment]
:+1: LGTM

**Pull request merged**
