### PR TITLE
Directory renaming

### PR DESCRIPTION
**Pull request by pevalme**
I have renamed folders and files and added a README for the regression-tests folder

### CODE REVIEW

**Comment by pierreganty** [comment]
I cannot do the automatic merge because your PR is not in sync with `pierreganty:master`
From `pevalme:directory_renaming`, I am reading
`This branch is 4 commits ahead, 15 commits behind pierreganty:master`.
Can you rebase so that I merge this PR?

**Comment by pevalme** [comment]
I have just rebased both pevalme:master and pevalme:directory_renaming. The merge should work now

**Comment by pierreganty** [comment]
It did not. See the `We can't automatically merge this pull request` right below.
Once the merge pull button gets enabled then I can merge.

**Comment by pierreganty** [comment]
one last thing. can you rebase because the list of your 9 commits looks weird?

**Comment by pierreganty** [comment]
:+1:

**Comment by pierreganty** [comment]
After merging #22, there is a `regression` folder but also a `regression-tests` folder. The former should go.

**Comment by pierreganty** [comment]
Choose the easiest path. If needed create another PR which deletes `regression`.

**Pull request merged**
