### PR TITLE
checking the network correctness

### PR DESCRIPTION
**Pull request by pevalme**
Right now, the parser checks if the substraction is valid or not but the program doesn't take care about the 'in' restriction yet

### CODE REVIEW

**Comment by pierreganty** [comment]
You use the word "limited". This is not what you mean. I'd rather say "constrained".
Also rebase the pull request and give it a more informative title like "Refined checking of input files".

**Comment by pierreganty** [comment]
Rename the pull request in something corresponding better to what the PR achieves.

**Comment by pierreganty** [comment]
ok but 'readed' is not english word

**Comment by pevalme** [comment]
I'll fix it right now

**Comment by pierreganty** [comment]
:+1: LGTM

**Pull request merged**
